DROP TABLE IDE_BLOG;
DROP SEQUENCE IDE_BLOGSEQ;

CREATE SEQUENCE IDE_BLOGSEQ;

CREATE TABLE IDE_BLOG(
	BLOG_SEQ NUMBER(10) PRIMARY KEY,
	MEM_EMAIL VARCHAR2(1000) NOT NULL,
	MEM_NAME VARCHAR2(1000) NOT NULL,
	MEM_PW VARCHAR2(1000) NOT NULL,
	BLOG_NAME VARCHAR2(1000) NOT NULL,
	BLOG_DESCRIPTION VARCHAR2(2000) NOT NULL,
	BLOG_LOGO VARCHAR2(2000) NOT NULL,
	CONSTRAINT FK_IDE_MEMBER FOREIGN KEY (MEM_EMAIL) 
	REFERENCES IDE_MEMBER (MEM_EMAIL)
	ON DELETE CASCADE 
);