DROP TABLE MEMBER;
DROP TABLE IDE_MEMBER;

CREATE TABLE IDE_MEMBER(
	MEM_EMAIL VARCHAR2(1000) PRIMARY KEY,
	MEM_NAME VARCHAR2(1000) NOT NULL,
	MEM_PW VARCHAR2(1000) NOT NULL
);

INSERT INTO IDE_MEMBER
VALUES('kdy41000@naver.com','김동영','1234');

SELECT * FROM IDE_MEMBER;